### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "user2",
  "password": "password",
  "phone": "01054325930",
  "role": "USER"
}

### 로그인

POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "name": "lee",
  "password": "password"

}

### 매장 등록

POST http://localhost:8080/store
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsZWUiLCJyb2xlIjoiQ0VPIiwiaWF0IjoxNzE5MTYyNTYwLCJleHAiOjE3MTkxNjYxNjB9.AtoCcEg_k90rPNOIphjGIhYpYDJDTCmutAu-QYYDGRwIsOhLIkdOxvyK4d_PyhTsmMLIXpVyR6gF8YIYFA8nSA



{
  "name": "loamart",
  "address": "주소",
  "description": "설명란"
}

### 매장 수정

PATCH http://localhost:8080/store
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsZWVnZW9uIiwicm9sZSI6IkNFTyIsImlhdCI6MTcxOTA4NDc0OSwiZXhwIjoxNzE5MDg4MzQ5fQ.IP30lwh9G4F4Xy1iJMavGK1U3bF4fw2qZ_fuWfMLfWDdXwfNPBWYhigm0qMzbVQGxEdG3nFhDDcj4oPwK6vz7A

{
  "storeId": 4,
  "address": "address",
  "description": "des"
}

### 매장 삭제

DELETE http://localhost:8080/store
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsZWVnZW9uIiwicm9sZSI6IkNFTyIsImlhdCI6MTcxOTE1NTg3NCwiZXhwIjoxNzE5MTU5NDc0fQ.GjXkyS4P09WBPVRDXyWzlYmSpmqskf5Rqd6v3rRopBJMWoxQyKBBX_StkbN9BC1CHZ7l78dW0m4QXB1q-suTxA

{
  "storeId": 4
}

### 매장 조회

GET http://localhost:8080/store?keyword=&page=0&size=10
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzE5MTY2NDQ5LCJleHAiOjE3MTkxNzAwNDl9.YvYO_-qPBgy9LB4Td0HqZEU0dJcr0RQMm-q2QsZ0uA9-0nMMBcd-wXT2HeCiyXEi3Ur_uVTGFGvBHEeyIB_gIA

### 매장 단건 조회

GET http://localhost:8080/store/7
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzE5MTY2NDQ5LCJleHAiOjE3MTkxNzAwNDl9.YvYO_-qPBgy9LB4Td0HqZEU0dJcr0RQMm-q2QsZ0uA9-0nMMBcd-wXT2HeCiyXEi3Ur_uVTGFGvBHEeyIB_gIA

### 매장 예약

POST http://localhost:8080/reservation
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzE5NDM0MTQxLCJleHAiOjE3MTk0Mzc3NDF9.nVIyC8BYEop4BIIEezrneeONPj5J8I8ma151bbEH8ubYozYnAw2Z7EGEa3AzNCqxU_akXh716txXLq_KyY1mpQ



{
  "storeId" : 7,
  "reserveTime" : "2024-06-28T14:00"
}

### 매장 방문확인

POST http://localhost:8080/reservation/visit
Content-Type: application/json

{
  "phone" : "01054325930",
  "visitedTime" : "2024-06-28T01:40",
  "storeId": 7
}

### 리뷰 작성

POST http://localhost:8080/review
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzE5NDM0MTQxLCJleHAiOjE3MTk0Mzc3NDF9.nVIyC8BYEop4BIIEezrneeONPj5J8I8ma151bbEH8ubYozYnAw2Z7EGEa3AzNCqxU_akXh716txXLq_KyY1mpQ

{
  "content" : "참dd 맛있네요",
  "star" : 3,
  "reservationId": 9
}


### 리뷰 수정

PATCH http://localhost:8080/review
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzE5NDM0MTQxLCJleHAiOjE3MTk0Mzc3NDF9.nVIyC8BYEop4BIIEezrneeONPj5J8I8ma151bbEH8ubYozYnAw2Z7EGEa3AzNCqxU_akXh716txXLq_KyY1mpQ

{
  "content" : "해킹이다",
  "star" : 5,
  "reviewId": 2
}

### 리뷰 삭제

DELETE http://localhost:8080/review
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsZWUiLCJyb2xlIjoiQ0VPIiwiaWF0IjoxNzE5NDM1MTAwLCJleHAiOjE3MTk0Mzg3MDB9.-d4Xw8Z8W7xksw-DEYtO3374xUAFBIBjZpDjIeSmOX6sKiiVazA5ts2Cg-QTLBc369sAzWiqmZYtpk8B4Wsecg



//Authorization: BEARER eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsZWUiLCJyb2xlIjoiQ0VPIiwiaWF0IjoxNzE5NDM0Mjc1LCJleHAiOjE3MTk0Mzc4NzV9.YKlYT-4Xpf3E54I9-zjINJajtP2cI7CNFV5emDacQ_jfzeXI2uBR2l2eWykhcbMFDuyvDe438yH74BS0dOF6yg


{
  "reviewId": 4
}

